"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import toast from "react-hot-toast";
import Loading from "@/components/Loading";
import BookingModal from "@/components/BookingModal";
import { apiFetch, syncServerToken } from "@/lib/api";
import { useSession } from "@/lib/auth-client";
export default function CarDetails(){const {id}=useParams(); const router=useRouter(); const [car,setCar]=useState(null),[loading,setLoading]=useState(true),[modal,setModal]=useState(false); const {data:session}=useSession(); useEffect(()=>{apiFetch(`/api/cars/${id}`).then(d=>setCar(d.car)).finally(()=>setLoading(false));},[id]); if(loading)return <Loading/>; if(!car)return <section className="container-page py-20"><h1 className="section-title">Car not found</h1></section>; const book=async()=>{if(!session?.user){toast.error("Please login to book a car"); router.push('/login'); return;} await syncServerToken(session.user); setModal(true);}; return <section className="container-page py-12"><div className="grid gap-8 lg:grid-cols-2"><img className="h-[520px] w-full rounded-[2rem] object-cover shadow-xl" src={car.image} alt={car.name}/><div className="card p-7"><p className="font-black uppercase tracking-[.2em] text-amber-600">{car.type}</p><h1 className="mt-2 text-4xl font-black">{car.name}</h1><p className="mt-4 text-lg text-slate-600">{car.description}</p><div className="mt-6 grid gap-3 rounded-3xl bg-slate-50 p-5 font-bold"><p>Daily Rent: ৳{car.price}</p><p>Seats: {car.seats}</p><p>Pickup Location: {car.location}</p><p>Status: {car.available ? 'Available' : 'Unavailable'}</p><p>Total Bookings: {car.booking_count || 0}</p><p>Owner: {car.ownerName || car.ownerEmail}</p></div><button disabled={!car.available} onClick={book} className="btn-primary mt-7 disabled:cursor-not-allowed disabled:opacity-60">Book Now</button></div></div>{modal&&<BookingModal car={car} user={session.user} onClose={(done)=>{setModal(false); if(done) apiFetch(`/api/cars/${id}`).then(d=>setCar(d.car));}}/>}</section>}
